### PR TITLE
Corrected the login issue and made some UI changes

### PR DESCRIPTION
**Pull request by Jitomorin**
- Made user object get stored in local storage
- But authcheck still checks if the user is present in the state not the local storage
- changed some designs and added logout functionality

### CODE REVIEW

**Comment by Kandy-Hamisi** [comment]
I have tested the login functionality under the vercel deployment.
The user in the localStorage is still set to null after logging in, hence I am just left in the login page.
In AuthCheck.jsx you need to fetch the use object from the localStorage so that It can work perfectly

**Comment by Jitomorin** [comment]
> I have tested the login functionality under the vercel deployment. The user in the localStorage is still set to null after logging in, hence I am just left in the login page. In AuthCheck.jsx you need to fetch the use object from the localStorage so that It can work perfectly

making it fetch user data from the local storage does not work.

**Comment by Jitomorin** [comment]
> > I have tested the login functionality under the vercel deployment. The user in the localStorage is still set to null after logging in, hence I am just left in the login page. In AuthCheck.jsx you need to fetch the use object from the localStorage so that It can work perfectly
> 
> making it fetch user data from the local storage does not work.

It is now working on my end, please confirm this.

**Comment by Kandy-Hamisi** [comment]
Tested it..it works

**Pull request merged**
